services:
  mariadb:
    image: mariadb:11.2.5
    container_name: mariadb
    environment:
      MYSQL_DATABASE: projects_db
      MYSQL_USER: nest_api
      MYSQL_PASSWORD: nest_api
      MARIADB_RANDOM_ROOT_PASSWORD: true
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql 
  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8080:8080"
    depends_on:
      - mariadb

volumes:
  mariadb_data: